### DISCUSSION TITLE
Welcome to node-red-contrib-NGSI-LD Discussions!

### DISCUSSION THREAD

**Discussion by fisuda** [lets-fiware/node-red-contrib-NGSI-LD#4] [Announcements]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

**Comment by johncaipa** [comment]
Hi @fisuda, thanks for this excellent node-red contribution, question regarding the broker config, I see that it is mandatory to put the Mintaka endpoint, but for example in my case I am using quantumleap with crateDB, in this case would there be any option to use these nodes? Or in the event that you do not use a temporary component, it would not be possible to use it?
![image](https://user-images.githubusercontent.com/31298276/233875951-f6d0ccb7-0d90-4b5b-b443-1dd6600be26e.png)
thanks in advance.

**Reply by fisuda** [reply]
In case of the following docker-compose.yml, set the broker endpoint to `http://orion-ld:1026` and set the mintaka endpoint to `http://mintaka:8080`. But, a node for temporal api is under developing. And, you can use the [NGSI timeseries node](https://github.com/lets-fiware/node-red-contrib-letsfiware-NGSI/blob/main/docs/en/custom_nodes/ngsi_timeseries.md) for Quantumleap.


```
version: "3"
services:
  orion-ld:
    image: fiware/orion-ld:1.1.2
    restart: always
    ports:
      - 1026:1026
    depends_on:
      - mongo
    restart: always
    environment:
      - ORIONLD_TROE=TRUE
      - ORIONLD_TROE_USER=orion
      - ORIONLD_TROE_PWD=orion
      - ORIONLD_TROE_HOST=timescale-db
      - ORIONLD_MONGO_HOST=mongo-db
      - ORIONLD_MULTI_SERVICE=TRUE
      - ORIONLD_DISABLE_FILE_LOG=TRUE
    command: -dbhost mongo -logLevel ERROR

  mongo:
    image: mongo:4.4
    restart: always

  mintaka:
    image: fiware/mintaka:0.5.35
    hostname: mintaka
    container_name: fiware-mintaka
    restart: always
    depends_on:
      - timescale-db
    environment:
      - DATASOURCES_DEFAULT_HOST=timescale-db
      - DATASOURCES_DEFAULT_USERNAME=orion
      - DATASOURCES_DEFAULT_PASSWORD=orion
      - DATASOURCES_DEFAULT_DATABASE=orion
      - DATASOURCES_DEFAULT_MAXIMUM_POOL_SIZE=2
      - ENDPOINTS_INFO_ENABLED=true
      - ENDPOINTS_INFO_SENSITIVE=false
    ports:
      - 8080:8080

  timescale-db:
    image: timescale/timescaledb-postgis:1.7.5-pg12
    hostname: timescale-db
    container_name: db-timescale
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U orion" ]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 60s
    environment:
      - POSTGRES_USER=orion
      - POSTGRES_PASSWORD=orion
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: ["postgres", "-c", "log_statement=none"]
    ports:
      - 5432:5432

  node-red:
    build: ./node-red
    image: letsfiware/node-red-local
    ports:
      - 1880:1880
```

Thanks
